apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-shell
  namespace: default
  labels:
    app: node-shell
spec:
  selector:
    matchLabels:
      app: node-shell
  template:
    metadata:
      labels:
        app: node-shell
    spec:
      # Access host namespaces
      hostPID: true
      hostNetwork: true
      hostIPC: true
      containers:
      - name: shell
        image: alpine
        securityContext:
          privileged: true
        # This command keeps the pod running so you can exec into it
        command: ["/bin/sh", "-c", "sleep infinity"]
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
